from Exercise_3_Try_Except import try_except
from Exercise_2_Input_Validation import int_num


try_except(8, 7)

int_num()